name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest
    
    # OIDC requires these permissions
    permissions:
      id-token: write   # Required to request OIDC token
      contents: read    # Required to checkout code
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::068741930680:role/github-actions-terraform-role
          aws-region: us-east-1
      
      - name: Sync frontend files to S3
        run: |
          aws s3 sync frontend/ s3://stratajen.net51343453413213243541 --delete
      
      - name: Invalidate CloudFront cache
        run: |
          aws cloudfront create-invalidation --distribution-id ELGFDIW5LH2XK --paths "/*"